id: P8E9577F2
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1CZ1011
  instance_id: http://purl.bdrc.io/resource/IE1KG4470
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - དྲང་ངེས་ལེགས་བཤད་སྙིང་པོ།
  alt_title:
    en:
    - dan-ne-leg-shed-nying-po
  author: http://purl.bdrc.io/resource/P64
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    075be51c0658495696a3c7b72570114a:
      title: པོད ༡་དྲང་ངེས་ལེགས་བཤད་སྙིང་པོ
      volume_number: 1
      base_file: UT1KG4470_I1KG4495_0000.txt
      reference: http://purl.bdrc.io/resource/VLE515C3BA42097FF5
      image_group: I1KG4495
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG4470
  - http://purl.bdrc.io/resource/MW1KG4470
  ocr_software: Namsel
created_at: '2021-12-22T10:42:03.015080'
last_modified_at: '2021-12-22T10:42:03.015086'
